name: Update Repository List

on: push
#  schedule:
#    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get repository list
        id: repo_list
        run: |
          REPO_LIST=$(curl -s -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/search/repositories?q=topic:llm+user:kayaozan+sort:author-date-asc" \
          | jq -r '.items')
          echo "list=$REPO_LIST" >> $GITHUB_OUTPUT

      - name: Update README
        run: |
          echo "# Repositories" > README.md
          echo "${{ list }}" >> README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update repository list'
          file: README.md
